#!/usr/bin/env python3
"""Generate plugin discovery and catalogs from existing component capability definitions."""
import argparse
import importlib.util
import json
from pathlib import Path
import re

_spec = importlib.util.spec_from_file_location('as_category_definitions', Path(__file__).with_name('validate-categories.py'))
categories = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(categories)

ADAPTER_NOTE = '> Host adapter: read [delivery-specific guidance](../../docs/host-adapters.md) for invocation, package paths, questions, file access and optional delegation.'
GENERATED_FROM = 'corpus/components.json'


def package_file(root, relative):
    path = categories.local_file(root, relative)
    current = root
    for part in Path(relative).parts:
        current = current / part
        if current.is_symlink():
            raise ValueError('capability reference uses a symlink: ' + relative)
    return path


def definitions(root):
    root = Path(root).resolve()
    components, _ = categories.validate(root)
    host_catalog = json.loads((root / 'corpus/host-contracts.json').read_text(encoding='utf-8'))
    output = []
    for key, component in sorted(components.items()):
        capability = component.get('capability')
        if capability is None:
            continue
        if component['category'] != 'skills':
            raise ValueError(key + ': capability metadata is scoped to skill entry points')
        if '\n' in capability['description'] or '\r' in capability['description']:
            raise ValueError(key + ': discovery description must be one line')
        if component['execution'] == 'instructions' and capability['executionOwner'] != 'host':
            raise ValueError(key + ': instruction workflow execution belongs to the host')
        if capability['hostContract'] != host_catalog['components'].get(key):
            raise ValueError(key + ': hostContract differs from the owning declaration catalog')
        contract = json.loads(package_file(root, capability['hostContract']).read_text(encoding='utf-8'))
        if contract['path'] != component['path']:
            raise ValueError(key + ': host contract instruction path differs')
        required = capability['references']
        common = {capability['hostContract'], 'docs/host-harness-contract.md', 'docs/host-adapters.md',
                  'docs/completion-reporting.md', 'corpus/host-contracts.json'}
        if not common <= set(required):
            raise ValueError(key + ': missing required host references')
        references = required + [row['path'] for row in capability.get('conditionalReferences', [])]
        if len(references) != len(set(references)):
            raise ValueError(key + ': duplicate or ambiguous required/conditional reference')
        for reference in references:
            package_file(root, reference)
        targets = set()
        for handoff in capability['handoffs']:
            target = handoff['target']
            if target not in components or components[target]['category'] != 'skills' or target in targets:
                raise ValueError(key + ': missing or duplicate handoff target ' + target)
            targets.add(target)
        instruction = package_file(root, component['path']).read_text(encoding='utf-8')
        if '](../../docs/host-adapters.md)' not in instruction:
            raise ValueError(key + ': missing shared delivery adapter reference')
        output.append({name: component[name] for name in ('id', 'path', 'execution', 'dependencies')} | capability)
    return output


def with_description(instruction, description):
    if not instruction.startswith('---\n') or '\n---\n' not in instruction[4:]:
        raise ValueError('skill frontmatter is missing or unterminated')
    frontmatter, body = instruction[4:].split('\n---\n', 1)
    replacement = 'description: ' + json.dumps(description, ensure_ascii=False)
    updated, count = re.subn(r'^description:.*(?:\n[ \t]+[^\n]*)*', lambda _: replacement, frontmatter, flags=re.M)
    if count != 1:
        raise ValueError('skill requires one description field')
    return '---\n' + updated + '\n---\n' + body


def markdown(rows):
    lines = ['# Capability discovery', '',
             '<!-- Generated by tools/validators/capabilities.py from corpus/components.json. Do not edit. -->', '',
             'This catalog covers the declared R2 critical paths. Other retained skills remain in the',
             '[full skill catalog](../skills/README.md). Definitions live only in the',
             '[component registry](../corpus/components.json); source instructions and references remain authoritative.', '',
             'These entries deliver workflow instructions. The host executes them after checking actual',
             'capabilities, project context and permission. Visibility is not selection, retrieval, execution',
             'or completion. A handoff preserves the current request and never authorizes an automatic chain.', '',
             '| Task | Capability | Execution owner |', '|---|---|---|']
    for row in rows:
        description = row['description'].replace('|', '\\|')
        lines.append(f"| {description} | [{row['id']}](../{row['path']}) | {row['executionOwner']} |")
    lines += ['', 'Machine consumers use [the generated JSON catalog](../corpus/capabilities.json).',
              '`references` are required package paths; `conditionalReferences` state when additional',
              'resources are needed. Dependency IDs express component relationships and are preserved',
              'separately. Use [host adapters](host-adapters.md) for actual invocation and retrieval.', '']
    return '\n'.join(lines)


def generate(root, write=False):
    root = Path(root).resolve()
    rows = definitions(root)
    planned = {}
    for row in rows:
        path = root / row['path']
        planned[path] = with_description(path.read_text(encoding='utf-8'), row['description'])
    catalog = dict(schema_version=1, generated_from=GENERATED_FROM,
                   generated_by='tools/validators/capabilities.py', capabilities=rows)
    planned[root / 'corpus/capabilities.json'] = json.dumps(catalog, ensure_ascii=False, indent=2) + '\n'
    planned[root / 'docs/capabilities.md'] = markdown(rows)
    stale = [str(path.relative_to(root)) for path, expected in planned.items()
             if not path.is_file() or path.read_text(encoding='utf-8') != expected]
    if write:
        for path, expected in planned.items():
            if str(path.relative_to(root)) in stale:
                path.write_text(expected, encoding='utf-8')
    elif stale:
        raise ValueError('stale generated capability metadata: ' + ', '.join(stale))
    return dict(valid=True, capabilities=len(rows), generated_from=GENERATED_FROM)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[2])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        print(json.dumps(generate(args.root, write=args.write)))
    except (ValueError, OSError, KeyError, TypeError) as error:
        parser.exit(2, f'capability metadata rejected: {error}\n')


if __name__ == '__main__':
    main()
